apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "split.fullname" . }}-keycloak-deployment
  namespace: split-{{ .Values.environment.name }}
  labels:
    app: {{ template "split.fullname" . }}
    chart: {{ template "split.chart" . }}
    component: "{{ .Values.keycloak.name }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "split.fullname" . }}
      component: "{{ .Values.keycloak.name }}"
      release: {{ .Release.Name }}
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: {{ template "split.fullname" . }}
        component: "{{ .Values.keycloak.name }}"
        release: {{ .Release.Name }}
    spec:
      securityContext:
        runAsUser: 1000
      containers:
        - name: {{ template "split.fullname" . }}-keycloak
          image: "{{ .Values.keycloak.image.repository }}:{{ .Values.keycloak.image.tag }}"
          imagePullPolicy: "{{ .Values.keycloak.image.pullPolicy }}"
          ports:
            - containerPort: {{ .Values.keycloak.port }}
          env:
           - name: KC_DB_URL
             valueFrom:
               secretKeyRef:
                 key: KC_DB_URL
                 name: split-keycloak-db-url
           - name: KEYCLOAK_ADMIN
             valueFrom:
               secretKeyRef:
                 key: KEYCLOAK_ADMIN
                 name: split-keycloak-admin
           - name: KEYCLOAK_ADMIN_PASSWORD
             valueFrom:
               secretKeyRef:
                 key: KEYCLOAK_ADMIN_PASSWORD
                 name: split-keycloak-admin-password
           - name: KC_HOSTNAME
             valueFrom:
               secretKeyRef:
                 key: KC_HOSTNAME
                 name: split-keycloak-hostname
          resources: {}
          livenessProbe:
            httpGet:
              port: {{ .Values.keycloak.port }}
              path: /health/ready
            initialDelaySeconds: 3
            periodSeconds: 3
      restartPolicy: Always
status: {}
