apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.applicationName }}-api-gateway-service
  namespace: split-{{ .Values.environment.name }}
  labels:
    app: {{ .Values.applicationName }}
    chart: {{ template "split.chart" . }}
    component: "{{ .Values.gateway.name }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.expensesService.port }}
      targetPort: {{ .Values.expensesService.port }}
  selector:
    app: {{ template "split.fullname" . }}
    component: "{{ .Values.gateway.name }}"
    release: {{ .Release.Name }}
