apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "split.fullname" . }}-ui-deployment
  namespace: split-{{ .Values.environment.name }}
  labels:
    app: {{ template "split.fullname" . }}
    chart: {{ template "split.chart" . }}
    component: "{{ .Values.ui.name }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "split.fullname" . }}
      component: "{{ .Values.ui.name }}"
      release: {{ .Release.Name }}
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: {{ template "split.fullname" . }}
        component: "{{ .Values.ui.name }}"
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "split.fullname" . }}-ui
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
          imagePullPolicy: "{{ .Values.ui.image.pullPolicy }}"
          livenessProbe:
            httpGet:
              port: {{ .Values.ui.port }}
              path: /
            initialDelaySeconds: 3
            periodSeconds: 3
      restartPolicy: Always
status: {}
