spring:
  profiles:
    active: default
    include: secret
mybatis:
  mapper-locations: config/mappers/*Mapper.xml
  type-aliases-package: io.jonathanlee.splitapiusersservice.domain
server:
  port: 8081
