server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/users
    username: root
    password: root
mybatis:
  mapper-locations: config/mappers/*Mapper.xml
  type-aliases-package: io.jonathanlee.splitapiusersservice.domain