server:
  port: 8081
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/split
          jwk-set-uri: http://localhost:8080/realms/split/protocol/openid-connect/certs
  cloud:
    gateway:
      routes:
        - id: users-route
          uri: ${USERS_ROUTE_URI:http://localhost:8082}
          predicates:
            - Path=/users/**
      default-filters:
        - TokenAuthHeader=
split:
  jwt:
    jwk-set-uri: http://localhost:8080/realms/split/protocol/openid-connect/certs