name: 'Docker Image Build & Push (Deploy to Staging)'

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build-and-push-services:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        service:
          - split-api-gateway
          - split-api-keycloak-service
          - split-api-mail-service
          - split-api-users-service
          - split-api-properties-service
          - split-api-expenses-service
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Get version
        run: |
          VERSION=$( mvn help:evaluate -Dexpression=project.version -q -DforceStdout )
          echo "::set-output name=version::$VERSION"
        id: get-version-from-pom
      - name: Maven Clean Install
        run: cd ${{ matrix.service }} && mvn clean install
      - name: Maven Build Docker Images
        run: cd ${{ matrix.service }} && mvn spring-boot:build-image
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: jonathanleedev
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish ${{ matrix.service }}
        run: docker push jonathanleedev/${{ matrix.service }}:${{ steps.get-version-from-pom.outputs.version }}